import sys
import os

repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, repo_root)

from scripts.lib.docmeta import parse_repo_index, parse_frontmatter

def main():
    manifest_path = os.path.join(repo_root, "manifest", "repo-index.yaml")
    if not os.path.exists(manifest_path):
        print(f"ERROR: Manifest not found at {manifest_path}")
        sys.exit(1)

    with open(manifest_path, "r") as f:
        manifest_data = parse_repo_index(f.read())

    out_lines = [
        "# SYSTEM_MAP",
        "",
        "This file is automatically generated from `manifest/repo-index.yaml` and the document frontmatter.",
        "It provides a complete overview of the canonical documentation zones and their contents.",
        ""
    ]

    for zone, zone_data in manifest_data.get("zones", {}).items():
        out_lines.append(f"## Zone: {zone}")
        out_lines.append("")
        path = zone_data.get("path", "")
        out_lines.append(f"**Path**: `{path}`")
        out_lines.append("")

        docs = zone_data.get("canonical_docs", [])
        if not docs:
            out_lines.append("_No documents listed in this zone._")
            out_lines.append("")
            continue

        out_lines.append("| ID | File | Status | Last Reviewed | Depends On |")
        out_lines.append("|---|---|---|---|---|")

        for doc_name in docs:
            display_path = os.path.join(path, doc_name)
            full_doc_path = os.path.join(repo_root, display_path)
            if not os.path.exists(full_doc_path):
                out_lines.append(f"| _Missing_ | `{display_path}` | _Missing_ | _Missing_ | _Missing_ |")
                continue

            with open(full_doc_path, "r") as df:
                frontmatter = parse_frontmatter(df.read())

            doc_id = frontmatter.get("id", "N/A")
            status = frontmatter.get("status", "N/A")
            last_reviewed = frontmatter.get("last_reviewed", "N/A")
            depends_on = ", ".join(frontmatter.get("depends_on", [])) or "-"

            out_lines.append(f"| {doc_id} | [{display_path}]({display_path}) | {status} | {last_reviewed} | {depends_on} |")

        out_lines.append("")

    out_lines.append("## Automated Checks")
    out_lines.append("")
    out_lines.append("The following checks verify the consistency and review status of the documents:")
    out_lines.append("")
    for check in manifest_data.get("checks", []):
        out_lines.append(f"- `{check}`")

    out_path = os.path.join(repo_root, "SYSTEM_MAP.md")
    with open(out_path, "w") as f:
        f.write("\n".join(out_lines) + "\n")

    print(f"Successfully generated {out_path}")

if __name__ == "__main__":
    main()
